"""turn number_of_items & total_price into hybrid properties

Revision ID: 0fa315999c7f
Revises: 25948d3a35b0
Create Date: 2024-11-11 17:06:25.432848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa315999c7f'
down_revision = '25948d3a35b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_orders')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('total_price')
        batch_op.drop_column('number_of_items')

    batch_op.alter_column(
            'created_at',
            server_default=sa.text("(NOW() AT TIME ZONE 'UTC')")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_items', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('total_price', sa.NUMERIC(precision=10, scale=2), nullable=False))

    op.create_table('_alembic_tmp_orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('order_type', sa.VARCHAR(), nullable=False),
    sa.Column('pickup_time', sa.DATETIME(), nullable=False),
    sa.Column('total_price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('order_status', sa.VARCHAR(), nullable=False),
    sa.Column('number_of_items', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_orders_customer_id_customers'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
