"""correct Order.number_of_items nullability

Revision ID: 25948d3a35b0
Revises: cdfcede04ca9
Create Date: 2024-11-11 15:52:52.112845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25948d3a35b0'
down_revision = 'cdfcede04ca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('number_of_items',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('number_of_items',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
